#include <cmath>
#include <simde/arm/neon.h>
#include <simde/mips/msa.h>
#include <simde/wasm/simd128.h>
#include <simde/x86/avx.h>
#include <simde/x86/avx2.h>
#include <simde/x86/avx512.h>
#include <simde/x86/clmul.h>
#include <simde/x86/f16c.h>
#include <simde/x86/fma.h>
#include <simde/x86/gfni.h>
#include <simde/x86/mmx.h>
#include <simde/x86/sse.h>
#include <simde/x86/sse2.h>
#include <simde/x86/sse3.h>
#include <simde/x86/sse4.1.h>
#include <simde/x86/sse4.2.h>
#include <simde/x86/ssse3.h>
#include <simde/x86/svml.h>
#include <simde/x86/xop.h>


// Inlude our extension of SIMDeX.
#include "../SIMDeX/mips/asub.h"
#include "../SIMDeX/mips/ave.h"
#include "../SIMDeX/mips/aver.h"
#include "../SIMDeX/mips/bclr.h"
#include "../SIMDeX/mips/bclri.h"
#include "../SIMDeX/mips/binsl.h"
#include "../SIMDeX/mips/binsli.h"
#include "../SIMDeX/mips/binsr.h"
#include "../SIMDeX/mips/binsri.h"
#include "../SIMDeX/mips/bmnz_v.h"
#include "../SIMDeX/mips/bmnzi.h"
#include "../SIMDeX/mips/bmz_v.h"
#include "../SIMDeX/mips/bmzi.h"
#include "../SIMDeX/mips/bneg.h"
#include "../SIMDeX/mips/bnegi.h"
#include "../SIMDeX/mips/bsel_v.h"
#include "../SIMDeX/mips/bseli.h"
#include "../SIMDeX/mips/bset.h"
#include "../SIMDeX/mips/bseti.h"
#include "../SIMDeX/mips/cast_to_scalar_double.h"
#include "../SIMDeX/mips/cast_to_scalar_float.h"
