#include <cmath>
#include <simde/arm/neon.h>
#include <simde/mips/msa.h>
#include <simde/wasm/simd128.h>
#include <simde/x86/avx.h>
#include <simde/x86/avx2.h>
#include <simde/x86/avx512.h>
#include <simde/x86/clmul.h>
#include <simde/x86/f16c.h>
#include <simde/x86/fma.h>
#include <simde/x86/gfni.h>
#include <simde/x86/mmx.h>
#include <simde/x86/sse.h>
#include <simde/x86/sse2.h>
#include <simde/x86/sse3.h>
#include <simde/x86/sse4.1.h>
#include <simde/x86/sse4.2.h>
#include <simde/x86/ssse3.h>
#include <simde/x86/svml.h>
#include <simde/x86/xop.h>


// Inlude our extension of SIMDeX.
#include "../SIMDeX/mips/asub.h"
#include "../SIMDeX/mips/ave.h"
#include "../SIMDeX/mips/aver.h"
#include "../SIMDeX/mips/bclr.h"
#include "../SIMDeX/mips/bclri.h"
#include "../SIMDeX/mips/binsl.h"
#include "../SIMDeX/mips/binsli.h"
#include "../SIMDeX/mips/binsr.h"
#include "../SIMDeX/mips/binsri.h"
#include "../SIMDeX/mips/bmnz_v.h"
#include "../SIMDeX/mips/bmnzi.h"
#include "../SIMDeX/mips/bmz_v.h"
#include "../SIMDeX/mips/bmzi.h"
#include "../SIMDeX/mips/bneg.h"
#include "../SIMDeX/mips/bnegi.h"
#include "../SIMDeX/mips/bsel_v.h"
#include "../SIMDeX/mips/bseli.h"
#include "../SIMDeX/mips/bset.h"
#include "../SIMDeX/mips/bseti.h"
#include "../SIMDeX/mips/cast_to_scalar_double.h"
#include "../SIMDeX/mips/cast_to_scalar_float.h"
#include "../SIMDeX/mips/cast_to_vector_double.h"
#include "../SIMDeX/mips/cast_to_vector_float.h"
#include "../SIMDeX/mips/ceq.h"
#include "../SIMDeX/mips/ceqi.h"
#include "../SIMDeX/mips/cfcmsa.h"
#include "../SIMDeX/mips/cle.h"
#include "../SIMDeX/mips/clei.h"
#include "../SIMDeX/mips/clt.h"
#include "../SIMDeX/mips/clti.h"
#include "../SIMDeX/mips/copy.h"
#include "../SIMDeX/mips/div.h"
#include "../SIMDeX/mips/dotp.h"
#include "../SIMDeX/mips/dpadd.h"
#include "../SIMDeX/mips/dpsub.h"
#include "../SIMDeX/mips/fadd.h"
#include "../SIMDeX/mips/fcaf.h"
#include "../SIMDeX/mips/fceq.h"
#include "../SIMDeX/mips/fclass.h"
#include "../SIMDeX/mips/fcle.h"
#include "../SIMDeX/mips/fclt.h"
#include "../SIMDeX/mips/fcne.h"
#include "../SIMDeX/mips/fcor.h"
#include "../SIMDeX/mips/fcueq.h"
#include "../SIMDeX/mips/fcule.h"
#include "../SIMDeX/mips/fcult.h"
#include "../SIMDeX/mips/fcun.h"
#include "../SIMDeX/mips/fcune.h"
#include "../SIMDeX/mips/fdiv.h"
#include "../SIMDeX/mips/fexdo.h"
#include "../SIMDeX/mips/fexp2.h"
#include "../SIMDeX/mips/fexupl.h"
#include "../SIMDeX/mips/fexupr.h"
#include "../SIMDeX/mips/ffint.h"
#include "../SIMDeX/mips/ffql.h"
#include "../SIMDeX/mips/ffqr.h"
#include "../SIMDeX/mips/fill.h"
#include "../SIMDeX/mips/flog2.h"
#include "../SIMDeX/mips/fmax.h"
#include "../SIMDeX/mips/fmax_a.h"
#include "../SIMDeX/mips/fmin.h"
#include "../SIMDeX/mips/fmin_a.h"
#include "../SIMDeX/mips/fmsub.h"
#include "../SIMDeX/mips/fmul.h"
#include "../SIMDeX/mips/frcp.h"
#include "../SIMDeX/mips/frint.h"
#include "../SIMDeX/mips/frsqrt.h"
#include "../SIMDeX/mips/fsaf.h"
#include "../SIMDeX/mips/fseq.h"
#include "../SIMDeX/mips/fsle.h"
#include "../SIMDeX/mips/fslt.h"
#include "../SIMDeX/mips/fsne.h"
#include "../SIMDeX/mips/fsor.h"
#include "../SIMDeX/mips/fsqrt.h"
#include "../SIMDeX/mips/fsub.h"
#include "../SIMDeX/mips/fsueq.h"
#include "../SIMDeX/mips/fsule.h"
#include "../SIMDeX/mips/fsult.h"
#include "../SIMDeX/mips/fsun.h"
#include "../SIMDeX/mips/fsune.h"
#include "../SIMDeX/mips/ftint.h"
#include "../SIMDeX/mips/ftq.h"
#include "../SIMDeX/mips/ftrunc.h"
#include "../SIMDeX/mips/hadd.h"
#include "../SIMDeX/mips/hsub.h"
#include "../SIMDeX/mips/ilvev.h"
