#include <cmath>
#include <simde/arm/neon.h>
#include <simde/mips/msa.h>
#include <simde/wasm/simd128.h>
#include <simde/x86/avx.h>
#include <simde/x86/avx2.h>
#include <simde/x86/avx512.h>
#include <simde/x86/clmul.h>
#include <simde/x86/f16c.h>
#include <simde/x86/fma.h>
#include <simde/x86/gfni.h>
#include <simde/x86/mmx.h>
#include <simde/x86/sse.h>
#include <simde/x86/sse2.h>
#include <simde/x86/sse3.h>
#include <simde/x86/sse4.1.h>
#include <simde/x86/sse4.2.h>
#include <simde/x86/ssse3.h>
#include <simde/x86/svml.h>
#include <simde/x86/xop.h>
