parser grammar ExprParser;

// Import the tokens generated by ExprLexer.
options { tokenVocab=ExprLexer; }

// The entry point.
prog: expr EOF ;

expr
    : expr op=(MUL | DIV) expr      # mulDiv
    | expr op=(ADD | SUB) expr      # addSub
    | '(' expr ')'                  # parens
    | constant                      # constValue
    ;

constant
    : PUREDEC_CONSTANT
    | BIN_CONSTANT
    | OCT_CONSTANT
    | HEX_CONSTANT
    | DEC_CONSTANT
    | FLOAT_CONSTANT
    ;
